// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzqRrNcnFIaQZhzcMl8jBl_5Jhn2cbpps',
    appId: '1:19166489760:web:843b6e3b62cb4de81e2dc5',
    messagingSenderId: '19166489760',
    projectId: 'el-sania-tech',
    authDomain: 'el-sania-tech.firebaseapp.com',
    storageBucket: 'el-sania-tech.firebasestorage.app',
    measurementId: 'G-RL151Q52Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtyMgc-WRwfXrGKelALJnkgBVRtXrzi00',
    appId: '1:19166489760:android:b64f2e2fb7f8830c1e2dc5',
    messagingSenderId: '19166489760',
    projectId: 'el-sania-tech',
    storageBucket: 'el-sania-tech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVUo0y81gJdFk8B18hA-nlKbH_lDul_WE',
    appId: '1:19166489760:ios:76f68931ef34f4aa1e2dc5',
    messagingSenderId: '19166489760',
    projectId: 'el-sania-tech',
    storageBucket: 'el-sania-tech.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVUo0y81gJdFk8B18hA-nlKbH_lDul_WE',
    appId: '1:19166489760:ios:76f68931ef34f4aa1e2dc5',
    messagingSenderId: '19166489760',
    projectId: 'el-sania-tech',
    storageBucket: 'el-sania-tech.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzqRrNcnFIaQZhzcMl8jBl_5Jhn2cbpps',
    appId: '1:19166489760:web:e8d3f63c147425f61e2dc5',
    messagingSenderId: '19166489760',
    projectId: 'el-sania-tech',
    authDomain: 'el-sania-tech.firebaseapp.com',
    storageBucket: 'el-sania-tech.firebasestorage.app',
    measurementId: 'G-0F2MH49FM8',
  );
}
